/*
 * OpenAI API
 * The OpenAI REST API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package space.fraktured.ai.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import space.fraktured.ai.client.model.ChatCompletionResponseMessage;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateChatCompletionResponseChoicesInner
 */
public class CreateChatCompletionResponseChoicesInnerTest {
    private final CreateChatCompletionResponseChoicesInner model = new CreateChatCompletionResponseChoicesInner();

    /**
     * Model tests for CreateChatCompletionResponseChoicesInner
     */
    @Test
    public void testCreateChatCompletionResponseChoicesInner() {
        // TODO: test CreateChatCompletionResponseChoicesInner
    }

    /**
     * Test the property 'index'
     */
    @Test
    public void indexTest() {
        // TODO: test index
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'finishReason'
     */
    @Test
    public void finishReasonTest() {
        // TODO: test finishReason
    }

}
