/*
 * OpenAI API
 * The OpenAI REST API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package space.fraktured.ai.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateEmbeddingResponseDataInner
 */
public class CreateEmbeddingResponseDataInnerTest {
    private final CreateEmbeddingResponseDataInner model = new CreateEmbeddingResponseDataInner();

    /**
     * Model tests for CreateEmbeddingResponseDataInner
     */
    @Test
    public void testCreateEmbeddingResponseDataInner() {
        // TODO: test CreateEmbeddingResponseDataInner
    }

    /**
     * Test the property 'index'
     */
    @Test
    public void indexTest() {
        // TODO: test index
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'embedding'
     */
    @Test
    public void embeddingTest() {
        // TODO: test embedding
    }

}
