/*
 * OpenAI API
 * The OpenAI REST API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package space.fraktured.ai.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateModerationResponseResultsInnerCategories
 */
public class CreateModerationResponseResultsInnerCategoriesTest {
    private final CreateModerationResponseResultsInnerCategories model = new CreateModerationResponseResultsInnerCategories();

    /**
     * Model tests for CreateModerationResponseResultsInnerCategories
     */
    @Test
    public void testCreateModerationResponseResultsInnerCategories() {
        // TODO: test CreateModerationResponseResultsInnerCategories
    }

    /**
     * Test the property 'hate'
     */
    @Test
    public void hateTest() {
        // TODO: test hate
    }

    /**
     * Test the property 'hateThreatening'
     */
    @Test
    public void hateThreateningTest() {
        // TODO: test hateThreatening
    }

    /**
     * Test the property 'selfHarm'
     */
    @Test
    public void selfHarmTest() {
        // TODO: test selfHarm
    }

    /**
     * Test the property 'sexual'
     */
    @Test
    public void sexualTest() {
        // TODO: test sexual
    }

    /**
     * Test the property 'sexualMinors'
     */
    @Test
    public void sexualMinorsTest() {
        // TODO: test sexualMinors
    }

    /**
     * Test the property 'violence'
     */
    @Test
    public void violenceTest() {
        // TODO: test violence
    }

    /**
     * Test the property 'violenceGraphic'
     */
    @Test
    public void violenceGraphicTest() {
        // TODO: test violenceGraphic
    }

}
