/*
 * OpenAI API
 * The OpenAI REST API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package space.fraktured.ai.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateFineTuneRequest
 */
public class CreateFineTuneRequestTest {
    private final CreateFineTuneRequest model = new CreateFineTuneRequest();

    /**
     * Model tests for CreateFineTuneRequest
     */
    @Test
    public void testCreateFineTuneRequest() {
        // TODO: test CreateFineTuneRequest
    }

    /**
     * Test the property 'trainingFile'
     */
    @Test
    public void trainingFileTest() {
        // TODO: test trainingFile
    }

    /**
     * Test the property 'validationFile'
     */
    @Test
    public void validationFileTest() {
        // TODO: test validationFile
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'nEpochs'
     */
    @Test
    public void nEpochsTest() {
        // TODO: test nEpochs
    }

    /**
     * Test the property 'batchSize'
     */
    @Test
    public void batchSizeTest() {
        // TODO: test batchSize
    }

    /**
     * Test the property 'learningRateMultiplier'
     */
    @Test
    public void learningRateMultiplierTest() {
        // TODO: test learningRateMultiplier
    }

    /**
     * Test the property 'promptLossWeight'
     */
    @Test
    public void promptLossWeightTest() {
        // TODO: test promptLossWeight
    }

    /**
     * Test the property 'computeClassificationMetrics'
     */
    @Test
    public void computeClassificationMetricsTest() {
        // TODO: test computeClassificationMetrics
    }

    /**
     * Test the property 'classificationNClasses'
     */
    @Test
    public void classificationNClassesTest() {
        // TODO: test classificationNClasses
    }

    /**
     * Test the property 'classificationPositiveClass'
     */
    @Test
    public void classificationPositiveClassTest() {
        // TODO: test classificationPositiveClass
    }

    /**
     * Test the property 'classificationBetas'
     */
    @Test
    public void classificationBetasTest() {
        // TODO: test classificationBetas
    }

    /**
     * Test the property 'suffix'
     */
    @Test
    public void suffixTest() {
        // TODO: test suffix
    }

}
