/*
 * OpenAI API
 * The OpenAI REST API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package space.fraktured.ai.client.model;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateChatCompletionRequestStop
 */
public class CreateChatCompletionRequestStopTest {
    private final CreateChatCompletionRequestStop model = new CreateChatCompletionRequestStop();

    /**
     * Model tests for CreateChatCompletionRequestStop
     */
    @Test
    public void testCreateChatCompletionRequestStop() {
        // TODO: test CreateChatCompletionRequestStop
    }

}
