/*
 * OpenAI API
 * The OpenAI REST API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package space.fraktured.ai.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateCompletionResponseChoicesInnerLogprobs
 */
public class CreateCompletionResponseChoicesInnerLogprobsTest {
    private final CreateCompletionResponseChoicesInnerLogprobs model = new CreateCompletionResponseChoicesInnerLogprobs();

    /**
     * Model tests for CreateCompletionResponseChoicesInnerLogprobs
     */
    @Test
    public void testCreateCompletionResponseChoicesInnerLogprobs() {
        // TODO: test CreateCompletionResponseChoicesInnerLogprobs
    }

    /**
     * Test the property 'tokens'
     */
    @Test
    public void tokensTest() {
        // TODO: test tokens
    }

    /**
     * Test the property 'tokenLogprobs'
     */
    @Test
    public void tokenLogprobsTest() {
        // TODO: test tokenLogprobs
    }

    /**
     * Test the property 'topLogprobs'
     */
    @Test
    public void topLogprobsTest() {
        // TODO: test topLogprobs
    }

    /**
     * Test the property 'textOffset'
     */
    @Test
    public void textOffsetTest() {
        // TODO: test textOffset
    }

}
