/*
 * OpenAI API
 * The OpenAI REST API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package space.fraktured.ai.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateAnswerResponseSelectedDocumentsInner
 */
public class CreateAnswerResponseSelectedDocumentsInnerTest {
    private final CreateAnswerResponseSelectedDocumentsInner model = new CreateAnswerResponseSelectedDocumentsInner();

    /**
     * Model tests for CreateAnswerResponseSelectedDocumentsInner
     */
    @Test
    public void testCreateAnswerResponseSelectedDocumentsInner() {
        // TODO: test CreateAnswerResponseSelectedDocumentsInner
    }

    /**
     * Test the property 'document'
     */
    @Test
    public void documentTest() {
        // TODO: test document
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

}
