/*
 * OpenAI API
 * The OpenAI REST API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package space.fraktured.ai.client.model;

import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateEmbeddingRequestInput
 */
public class CreateEmbeddingRequestInputTest {
    private final CreateEmbeddingRequestInput model = new CreateEmbeddingRequestInput();

    /**
     * Model tests for CreateEmbeddingRequestInput
     */
    @Test
    public void testCreateEmbeddingRequestInput() {
        // TODO: test CreateEmbeddingRequestInput
    }

}
