/*
 * OpenAI API
 * The OpenAI REST API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package space.fraktured.ai.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import space.fraktured.ai.client.model.CreateAnswerRequestStop;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateAnswerRequest
 */
public class CreateAnswerRequestTest {
    private final CreateAnswerRequest model = new CreateAnswerRequest();

    /**
     * Model tests for CreateAnswerRequest
     */
    @Test
    public void testCreateAnswerRequest() {
        // TODO: test CreateAnswerRequest
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'question'
     */
    @Test
    public void questionTest() {
        // TODO: test question
    }

    /**
     * Test the property 'examples'
     */
    @Test
    public void examplesTest() {
        // TODO: test examples
    }

    /**
     * Test the property 'examplesContext'
     */
    @Test
    public void examplesContextTest() {
        // TODO: test examplesContext
    }

    /**
     * Test the property 'documents'
     */
    @Test
    public void documentsTest() {
        // TODO: test documents
    }

    /**
     * Test the property '_file'
     */
    @Test
    public void _fileTest() {
        // TODO: test _file
    }

    /**
     * Test the property 'searchModel'
     */
    @Test
    public void searchModelTest() {
        // TODO: test searchModel
    }

    /**
     * Test the property 'maxRerank'
     */
    @Test
    public void maxRerankTest() {
        // TODO: test maxRerank
    }

    /**
     * Test the property 'temperature'
     */
    @Test
    public void temperatureTest() {
        // TODO: test temperature
    }

    /**
     * Test the property 'logprobs'
     */
    @Test
    public void logprobsTest() {
        // TODO: test logprobs
    }

    /**
     * Test the property 'maxTokens'
     */
    @Test
    public void maxTokensTest() {
        // TODO: test maxTokens
    }

    /**
     * Test the property 'stop'
     */
    @Test
    public void stopTest() {
        // TODO: test stop
    }

    /**
     * Test the property 'n'
     */
    @Test
    public void nTest() {
        // TODO: test n
    }

    /**
     * Test the property 'logitBias'
     */
    @Test
    public void logitBiasTest() {
        // TODO: test logitBias
    }

    /**
     * Test the property 'returnMetadata'
     */
    @Test
    public void returnMetadataTest() {
        // TODO: test returnMetadata
    }

    /**
     * Test the property 'returnPrompt'
     */
    @Test
    public void returnPromptTest() {
        // TODO: test returnPrompt
    }

    /**
     * Test the property 'expand'
     */
    @Test
    public void expandTest() {
        // TODO: test expand
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

}
