/*
 * OpenAI API
 * The OpenAI REST API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package space.fraktured.ai.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import space.fraktured.ai.client.model.CreateModerationResponseResultsInnerCategories;
import space.fraktured.ai.client.model.CreateModerationResponseResultsInnerCategoryScores;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateModerationResponseResultsInner
 */
public class CreateModerationResponseResultsInnerTest {
    private final CreateModerationResponseResultsInner model = new CreateModerationResponseResultsInner();

    /**
     * Model tests for CreateModerationResponseResultsInner
     */
    @Test
    public void testCreateModerationResponseResultsInner() {
        // TODO: test CreateModerationResponseResultsInner
    }

    /**
     * Test the property 'flagged'
     */
    @Test
    public void flaggedTest() {
        // TODO: test flagged
    }

    /**
     * Test the property 'categories'
     */
    @Test
    public void categoriesTest() {
        // TODO: test categories
    }

    /**
     * Test the property 'categoryScores'
     */
    @Test
    public void categoryScoresTest() {
        // TODO: test categoryScores
    }

}
