/*
 * OpenAI API
 * The OpenAI REST API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package space.fraktured.ai.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import space.fraktured.ai.client.model.FineTuneEvent;
import space.fraktured.ai.client.model.OpenAIFile;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FineTune
 */
public class FineTuneTest {
    private final FineTune model = new FineTune();

    /**
     * Model tests for FineTune
     */
    @Test
    public void testFineTune() {
        // TODO: test FineTune
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'fineTunedModel'
     */
    @Test
    public void fineTunedModelTest() {
        // TODO: test fineTunedModel
    }

    /**
     * Test the property 'organizationId'
     */
    @Test
    public void organizationIdTest() {
        // TODO: test organizationId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'hyperparams'
     */
    @Test
    public void hyperparamsTest() {
        // TODO: test hyperparams
    }

    /**
     * Test the property 'trainingFiles'
     */
    @Test
    public void trainingFilesTest() {
        // TODO: test trainingFiles
    }

    /**
     * Test the property 'validationFiles'
     */
    @Test
    public void validationFilesTest() {
        // TODO: test validationFiles
    }

    /**
     * Test the property 'resultFiles'
     */
    @Test
    public void resultFilesTest() {
        // TODO: test resultFiles
    }

    /**
     * Test the property 'events'
     */
    @Test
    public void eventsTest() {
        // TODO: test events
    }

}
