openapi: 3.0.0
info:
  title: OpenAI Realtime API
  description: This is the OpenAI Realtime API specification.
  version: 1.0.0
paths:
  /realtime:
    get:
      summary: Get real-time updates
      description: Retrieve real-time updates from the OpenAI platform.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  event:
                    type: string
                    description: The event type
                  data:
                    type: object
                    description: The event data
