/*
 * OpenAI API
 * The OpenAI REST API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package space.fraktured.ai.client.api;

import space.fraktured.ai.client.ApiException;
import java.math.BigDecimal;
import space.fraktured.ai.client.model.CreateTranscriptionResponse;
import space.fraktured.ai.client.model.CreateTranslationResponse;
import java.io.File;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AudioApi
 */
@Disabled
public class AudioApiTest {

    private final AudioApi api = new AudioApi();

    /**
     * Create Transcription
     *
     * Transcribes audio into the input language.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createTranscriptionTest() throws ApiException {
        File _file = null;
        String model = null;
        String prompt = null;
        String responseFormat = null;
        BigDecimal temperature = null;
        String language = null;
        CreateTranscriptionResponse response = api.createTranscription(_file, model, prompt, responseFormat, temperature, language);
        // TODO: test validations
    }

    /**
     * Create Translation
     *
     * Translates audio into into English.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createTranslationTest() throws ApiException {
        File _file = null;
        String model = null;
        String prompt = null;
        String responseFormat = null;
        BigDecimal temperature = null;
        CreateTranslationResponse response = api.createTranslation(_file, model, prompt, responseFormat, temperature);
        // TODO: test validations
    }

}
