/*
 * OpenAI API
 * The OpenAI REST API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package space.fraktured.ai.client.api;

import space.fraktured.ai.client.ApiException;
import space.fraktured.ai.client.model.CreateFineTuneRequest;
import space.fraktured.ai.client.model.FineTune;
import space.fraktured.ai.client.model.ListFineTuneEventsResponse;
import space.fraktured.ai.client.model.ListFineTunesResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FineTunesApi
 */
@Disabled
public class FineTunesApiTest {

    private final FineTunesApi api = new FineTunesApi();

    /**
     * Cancel Fine Tune
     *
     * Immediately cancel a fine-tune job. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cancelFineTuneTest() throws ApiException {
        String fineTuneId = null;
        FineTune response = api.cancelFineTune(fineTuneId);
        // TODO: test validations
    }

    /**
     * Create Fine Tune
     *
     * Creates a job that fine-tunes a specified model from a given dataset.  Response includes details of the enqueued job including job status and the name of the fine-tuned models once complete.  [Learn more about Fine-tuning](/docs/guides/fine-tuning) 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createFineTuneTest() throws ApiException {
        CreateFineTuneRequest createFineTuneRequest = null;
        FineTune response = api.createFineTune(createFineTuneRequest);
        // TODO: test validations
    }

    /**
     * List Fine Tune Events
     *
     * Get fine-grained status updates for a fine-tune job. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listFineTuneEventsTest() throws ApiException {
        String fineTuneId = null;
        Boolean stream = null;
        ListFineTuneEventsResponse response = api.listFineTuneEvents(fineTuneId, stream);
        // TODO: test validations
    }

    /**
     * List Fine Tunes
     *
     * List your organization&#39;s fine-tuning jobs 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listFineTunesTest() throws ApiException {
        ListFineTunesResponse response = api.listFineTunes();
        // TODO: test validations
    }

    /**
     * Retrieve Fine Tune
     *
     * Gets info about the fine-tune job.  [Learn more about Fine-tuning](/docs/guides/fine-tuning) 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void retrieveFineTuneTest() throws ApiException {
        String fineTuneId = null;
        FineTune response = api.retrieveFineTune(fineTuneId);
        // TODO: test validations
    }

}
